image: python:latest

pages:
  stage: deploy
  script:
  - apt-get update
  #- apt-get install -y python3-sphinx
  # - make html
  #- cp -R -T build/html public
  artifacts:
    paths:
    - public
  only:
  - main
 
 
